try:
    from envs.multi_quadcopter_drone_env import ENV_DEFAULTS
except ImportError:
    from quad_physics.envs.multi_quadcopter_drone_env import ENV_DEFAULTS


config = {
    **ENV_DEFAULTS,
    "run_name": "quad_physics_mappo_fixed_v12",
    "seed": 7,
    "max_tilt": 0.35,
    "linear_drag": 0.75,
    "attitude_tau": 0.18,
    "angular_damping": 0.82,
    "rollout_steps": 1024,
    "epochs": 6,
    "minibatch_size": 256,
    "learning_rate": 3e-4,
    "gamma": 0.99,
    "gae_lambda": 0.95,
    "clip_range": 0.15,
    "ent_coef": 0.004,
    "vf_coef": 0.5,
    "max_grad_norm": 0.5,
    "hidden_size": 128,
    "progress_print_freq": 10_000,
    "stage_eval_every": 40_000,
    "stage_eval_episodes": 20,
    "stage_promotion_success_rate": 0.75,
    "stage_min_timesteps_before_promotion": 80_000,
    "viz_enabled": True,
    "viz_delay": 0.12,
    "viz_save_path": "mappo_fixed_quad_rollout.gif",
    "viz_save_images": True,
    "viz_image_dir": "mappo_fixed_quad_rollout_images",
    "viz_show": False,
    "resume_from_checkpoint": None,
    "resume_stage_name": None,
    "curriculum": [
        {
            "name": "s1_short_t_fixed",
            "map_layout": "t_junction",
            "stem_length": 4,
            "branch_left": 1,
            "branch_right": 1,
            "map_padding": 1,
            "max_steps": 120,
            "timesteps": 180_000,
            "fixed_starts": [[4, 2], [3, 2]],
            "fixed_package": [2, 2],
            "fixed_deliveries": [[1, 1], [1, 3]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 20_000,
            "min_timesteps_before_promotion": 60_000,
            "promotion_success_rate": 0.90,
            "collision_penalty": 8.0,
            "revisit_penalty": 0.0,
            "revisit_penalty_cap": 0.0,
        },
        {
            "name": "s2_wider_t_stem_fixed",
            "map_layout": "t_junction",
            "stem_length": 6,
            "branch_left": 3,
            "branch_right": 3,
            "map_padding": 1,
            "max_steps": 220,
            "timesteps": 540_000,
            "fixed_starts": [[6, 4], [5, 4]],
            "fixed_package": [3, 4],
            "fixed_deliveries": [[2, 4], [1, 4]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 25_000,
            "min_timesteps_before_promotion": 80_000,
            "promotion_success_rate": 0.85,
            "collision_penalty": 8.0,
            "revisit_penalty": 0.0,
            "revisit_penalty_cap": 0.0,
        },
        {
            "name": "s3_wider_t_near_branch_fixed",
            "map_layout": "t_junction",
            "stem_length": 6,
            "branch_left": 3,
            "branch_right": 3,
            "map_padding": 1,
            "max_steps": 280,
            "timesteps": 750_000,
            "fixed_starts": [[6, 4], [5, 4]],
            "fixed_package": [2, 4],
            "fixed_deliveries": [[1, 3], [1, 5]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 25_000,
            "min_timesteps_before_promotion": 100_000,
            "promotion_success_rate": 0.75,
            "collision_penalty": 8.0,
            "revisit_penalty": 0.0,
            "revisit_penalty_cap": 0.0,
        },
        {
            "name": "s4a_wider_t_branch_near_fixed",
            "map_layout": "t_junction",
            "stem_length": 6,
            "branch_left": 3,
            "branch_right": 3,
            "map_padding": 1,
            "max_steps": 300,
            "timesteps": 450_000,
            "fixed_starts": [[6, 4], [5, 4]],
            "fixed_package": [3, 4],
            "fixed_deliveries": [[1, 3], [1, 5]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 25_000,
            "min_timesteps_before_promotion": 80_000,
            "promotion_success_rate": 0.80,
            "collision_penalty": 8.0,
            "revisit_penalty": 0.0,
            "revisit_penalty_cap": 0.0,
        },
        {
            "name": "s4b_left_wider_t_branch_mid_fixed",
            "map_layout": "t_junction",
            "stem_length": 6,
            "branch_left": 3,
            "branch_right": 3,
            "map_padding": 1,
            "max_steps": 320,
            "timesteps": 450_000,
            "fixed_starts": [[6, 4], [5, 4]],
            "fixed_package": [3, 4],
            "fixed_deliveries": [[1, 2], [1, 5]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 25_000,
            "min_timesteps_before_promotion": 80_000,
            "promotion_success_rate": 0.75,
            "collision_penalty": 8.0,
            "revisit_penalty": 0.0,
            "revisit_penalty_cap": 0.0,
        },
        {
            "name": "s4c_right_wider_t_branch_mid_fixed",
            "map_layout": "t_junction",
            "stem_length": 6,
            "branch_left": 3,
            "branch_right": 3,
            "map_padding": 1,
            "max_steps": 320,
            "timesteps": 450_000,
            "fixed_starts": [[6, 4], [5, 4]],
            "fixed_package": [3, 4],
            "fixed_deliveries": [[1, 3], [1, 6]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 25_000,
            "min_timesteps_before_promotion": 80_000,
            "promotion_success_rate": 0.75,
            "collision_penalty": 8.0,
            "revisit_penalty": 0.0,
            "revisit_penalty_cap": 0.0,
        },
        {
            "name": "s4d_wider_t_branch_mid_fixed",
            "map_layout": "t_junction",
            "stem_length": 6,
            "branch_left": 3,
            "branch_right": 3,
            "map_padding": 1,
            "max_steps": 330,
            "timesteps": 650_000,
            "fixed_starts": [[6, 4], [5, 4]],
            "fixed_package": [3, 4],
            "fixed_deliveries": [[1, 2], [1, 6]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 25_000,
            "min_timesteps_before_promotion": 100_000,
            "promotion_success_rate": 0.70,
            "collision_penalty": 8.0,
            "revisit_penalty": 0.0,
            "revisit_penalty_cap": 0.0,
        },
        {
            "name": "s4e_wider_t_branch_far_fixed",
            "map_layout": "t_junction",
            "stem_length": 6,
            "branch_left": 3,
            "branch_right": 3,
            "map_padding": 1,
            "max_steps": 340,
            "timesteps": 850_000,
            "fixed_starts": [[6, 4], [5, 4]],
            "fixed_package": [3, 4],
            "fixed_deliveries": [[1, 1], [1, 7]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 30_000,
            "min_timesteps_before_promotion": 120_000,
            "promotion_success_rate": 0.70,
            "collision_penalty": 8.0,
            "revisit_penalty": 0.0,
            "revisit_penalty_cap": 0.0,
        },
        {
            "name": "s5_tiny_pipe_line_fixed",
            "grid_size": [2, 2],
            "map_seed": 42,
            "loop_prob": 0.25,
            "max_steps": 260,
            "timesteps": 260_000,
            "fixed_starts": [[2, 3], [2, 4]],
            "fixed_package": [2, 5],
            "fixed_deliveries": [[2, 6], [2, 7]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 25_000,
            "min_timesteps_before_promotion": 80_000,
            "promotion_success_rate": 0.80,
            "actor_log_std": -0.35,
            "min_actor_log_std": -0.75,
            "collision_penalty": 8.0,
        },
        {
            "name": "s6_small_pipe_line_fixed",
            "grid_size": [3, 3],
            "map_seed": 101,
            "loop_prob": 0.25,
            "max_steps": 360,
            "timesteps": 360_000,
            "fixed_starts": [[2, 3], [2, 4]],
            "fixed_package": [2, 6],
            "fixed_deliveries": [[2, 8], [2, 9]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 25_000,
            "min_timesteps_before_promotion": 90_000,
            "promotion_success_rate": 0.80,
            "actor_log_std": -0.35,
            "min_actor_log_std": -0.75,
            "collision_penalty": 8.0,
            "revisit_penalty": 0.0,
            "revisit_penalty_cap": 0.0,
        },
        {
            "name": "s7_small_pipe_vertical_fixed",
            "grid_size": [3, 3],
            "map_seed": 101,
            "loop_prob": 0.25,
            "max_steps": 360,
            "timesteps": 360_000,
            "fixed_starts": [[2, 8], [3, 8]],
            "fixed_package": [4, 8],
            "fixed_deliveries": [[5, 8], [6, 8]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 25_000,
            "min_timesteps_before_promotion": 90_000,
            "promotion_success_rate": 0.80,
            "actor_log_std": -0.35,
            "min_actor_log_std": -0.75,
            "ent_coef": 0.012,
            "collision_penalty": 8.0,
            "revisit_penalty": 0.0,
            "revisit_penalty_cap": 0.0,
        },
        {
            "name": "s8_small_pipe_turn_fixed",
            "grid_size": [3, 3],
            "map_seed": 101,
            "loop_prob": 0.25,
            "max_steps": 460,
            "timesteps": 500_000,
            "fixed_starts": [[2, 6], [2, 7]],
            "fixed_package": [2, 8],
            "fixed_deliveries": [[4, 8], [5, 8]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 25_000,
            "min_timesteps_before_promotion": 90_000,
            "promotion_success_rate": 0.75,
            "actor_log_std": -0.35,
            "min_actor_log_std": -0.75,
            "ent_coef": 0.012,
            "collision_penalty": 8.0,
            "revisit_penalty": 0.0,
            "revisit_penalty_cap": 0.0,
        },
        {
            "name": "s9a_small_pipe_rejoin_fixed",
            "grid_size": [3, 3],
            "map_seed": 101,
            "loop_prob": 0.25,
            "max_steps": 560,
            "timesteps": 520_000,
            "fixed_starts": [[2, 3], [2, 4]],
            "fixed_package": [2, 8],
            "fixed_deliveries": [[6, 8], [7, 8]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 25_000,
            "min_timesteps_before_promotion": 90_000,
            "promotion_success_rate": 0.75,
            "actor_log_std": -0.35,
            "min_actor_log_std": -0.75,
            "ent_coef": 0.010,
        },
        {
            "name": "s9b_small_pipe_package_step_fixed",
            "grid_size": [3, 3],
            "map_seed": 101,
            "loop_prob": 0.25,
            "max_steps": 620,
            "timesteps": 650_000,
            "fixed_starts": [[2, 3], [2, 4]],
            "fixed_package": [3, 8],
            "fixed_deliveries": [[6, 8], [7, 8]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 30_000,
            "min_timesteps_before_promotion": 100_000,
            "promotion_success_rate": 0.70,
            "actor_log_std": -0.35,
            "min_actor_log_std": -0.75,
            "ent_coef": 0.010,
        },
        {
            "name": "s9c_small_pipe_delivery_step_fixed",
            "grid_size": [3, 3],
            "map_seed": 101,
            "loop_prob": 0.25,
            "max_steps": 760,
            "timesteps": 760_000,
            "fixed_starts": [[2, 3], [2, 4]],
            "fixed_package": [4, 8],
            "fixed_deliveries": [[6, 9], [7, 9]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 35_000,
            "min_timesteps_before_promotion": 110_000,
            "promotion_success_rate": 0.70,
            "actor_log_std": -0.35,
            "min_actor_log_std": -0.75,
            "ent_coef": 0.010,
        },
        {
            "name": "s9d_small_pipe_fixed",
            "grid_size": [3, 3],
            "map_seed": 101,
            "loop_prob": 0.25,
            "max_steps": 900,
            "timesteps": 880_000,
            "fixed_starts": [[2, 3], [2, 4]],
            "fixed_package": [4, 8],
            "fixed_deliveries": [[8, 13], [9, 12]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 40_000,
            "min_timesteps_before_promotion": 120_000,
            "promotion_success_rate": 0.65,
            "actor_log_std": -0.35,
            "min_actor_log_std": -0.75,
            "ent_coef": 0.010,
        },
        {
            "name": "s10a_pipe_4x4_entry_fixed",
            "grid_size": [4, 4],
            "map_seed": 202,
            "loop_prob": 0.30,
            "max_steps": 900,
            "timesteps": 520_000,
            "fixed_starts": [[2, 3], [2, 4]],
            "fixed_package": [6, 3],
            "fixed_deliveries": [[9, 2], [10, 3]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 35_000,
            "min_timesteps_before_promotion": 100_000,
            "promotion_success_rate": 0.70,
            "continue_success_rate": 0.45,
            "actor_log_std": -0.35,
            "min_actor_log_std": -0.75,
            "ent_coef": 0.010,
        },
        {
            "name": "s10b_pipe_4x4_mid_package_fixed",
            "grid_size": [4, 4],
            "map_seed": 202,
            "loop_prob": 0.30,
            "max_steps": 1000,
            "timesteps": 650_000,
            "fixed_starts": [[2, 3], [2, 4]],
            "fixed_package": [8, 3],
            "fixed_deliveries": [[11, 2], [12, 3]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 40_000,
            "min_timesteps_before_promotion": 110_000,
            "promotion_success_rate": 0.70,
            "continue_success_rate": 0.45,
            "actor_log_std": -0.35,
            "min_actor_log_std": -0.75,
            "ent_coef": 0.010,
        },
        {
            "name": "s10c_pipe_4x4_longer_package_fixed",
            "grid_size": [4, 4],
            "map_seed": 202,
            "loop_prob": 0.30,
            "max_steps": 1150,
            "timesteps": 760_000,
            "fixed_starts": [[2, 3], [2, 4]],
            "fixed_package": [10, 3],
            "fixed_deliveries": [[14, 7], [15, 6]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 45_000,
            "min_timesteps_before_promotion": 120_000,
            "promotion_success_rate": 0.65,
            "continue_success_rate": 0.40,
            "actor_log_std": -0.35,
            "min_actor_log_std": -0.75,
            "ent_coef": 0.010,
        },
        {
            "name": "s10d_pipe_4x4_turn_bridge_fixed",
            "grid_size": [4, 4],
            "map_seed": 202,
            "loop_prob": 0.30,
            "max_steps": 1300,
            "timesteps": 780_000,
            "fixed_starts": [[2, 3], [2, 4]],
            "fixed_package": [14, 3],
            "fixed_deliveries": [[14, 13], [15, 12]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 50_000,
            "min_timesteps_before_promotion": 140_000,
            "promotion_success_rate": 0.60,
            "continue_success_rate": 0.35,
            "actor_log_std": -0.20,
            "min_actor_log_std": -0.90,
            "ent_coef": 0.014,
            "revisit_penalty": 0.0,
            "revisit_penalty_cap": 0.0,
        },
        {
            "name": "s10e_pipe_4x4_fixed",
            "grid_size": [4, 4],
            "map_seed": 202,
            "loop_prob": 0.30,
            "max_steps": 1700,
            "timesteps": 1_500_000,
            "fixed_starts": [[2, 3], [2, 4]],
            "fixed_package": [14, 3],
            "fixed_deliveries": [[18, 15], [19, 14]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 60_000,
            "min_timesteps_before_promotion": 220_000,
            "promotion_success_rate": 0.55,
            "continue_success_rate": 0.25,
            "actor_log_std": -0.15,
            "min_actor_log_std": -0.95,
            "ent_coef": 0.016,
            "revisit_penalty": 0.0,
            "revisit_penalty_cap": 0.0,
        },
        {
            "name": "s11_pipe_6x6_fixed",
            "grid_size": [6, 6],
            "map_seed": 303,
            "loop_prob": 0.30,
            "max_steps": 1800,
            "timesteps": 950_000,
            "package_min_dist": 8,
            "package_max_dist": 16,
            "delivery_min_dist": 7,
            "delivery_max_dist": 18,
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 60_000,
            "min_timesteps_before_promotion": 100_000,
            "promotion_success_rate": 0.65,
            "continue_success_rate": 0.45,
            "rollout_steps": 2048,
            "minibatch_size": 512,
            "ent_coef": 0.010,
        },
        {
            "name": "s12_pipe_8x8_local_fixed",
            "grid_size": [8, 8],
            "map_seed": 404,
            "loop_prob": 0.35,
            "max_steps": 500,
            "timesteps": 420_000,
            "fixed_starts": [[7, 8], [8, 8]],
            "fixed_package": [8, 9],
            "fixed_deliveries": [[9, 9], [7, 9]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 35_000,
            "min_timesteps_before_promotion": 100_000,
            "promotion_success_rate": 0.85,
            "continue_success_rate": 0.60,
            "actor_log_std": -0.30,
            "min_actor_log_std": -0.75,
            "rollout_steps": 1024,
            "minibatch_size": 256,
            "ent_coef": 0.010,
            "collision_penalty": 8.0,
            "revisit_penalty": 0.0,
            "revisit_penalty_cap": 0.0,
        },
        {
            "name": "s13_pipe_8x8_near_fixed",
            "grid_size": [8, 8],
            "map_seed": 404,
            "loop_prob": 0.35,
            "max_steps": 1200,
            "timesteps": 850_000,
            "fixed_starts": [[2, 3], [2, 4]],
            "fixed_package": [8, 9],
            "fixed_deliveries": [[9, 9], [7, 9]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 50_000,
            "min_timesteps_before_promotion": 100_000,
            "promotion_success_rate": 0.75,
            "continue_success_rate": 0.50,
            "rollout_steps": 2048,
            "minibatch_size": 512,
            "ent_coef": 0.008,
        },
        {
            "name": "s14_pipe_8x8_delivery_west_bridge_fixed",
            "grid_size": [8, 8],
            "map_seed": 404,
            "loop_prob": 0.35,
            "max_steps": 1400,
            "timesteps": 650_000,
            "fixed_starts": [[2, 3], [2, 4]],
            "fixed_package": [8, 9],
            "fixed_deliveries": [[8, 8], [9, 8]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 55_000,
            "min_timesteps_before_promotion": 100_000,
            "promotion_success_rate": 0.65,
            "continue_success_rate": 0.40,
            "actor_log_std": -0.25,
            "min_actor_log_std": -0.80,
            "rollout_steps": 2048,
            "minibatch_size": 512,
            "ent_coef": 0.012,
        },
        {
            "name": "s15_pipe_8x8_pkg_west_bridge1_fixed",
            "grid_size": [8, 8],
            "map_seed": 404,
            "loop_prob": 0.35,
            "max_steps": 1600,
            "timesteps": 750_000,
            "fixed_starts": [[2, 3], [2, 4]],
            "fixed_package": [8, 8],
            "fixed_deliveries": [[8, 7], [9, 8]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 60_000,
            "min_timesteps_before_promotion": 120_000,
            "promotion_success_rate": 0.60,
            "continue_success_rate": 0.35,
            "actor_log_std": -0.25,
            "min_actor_log_std": -0.80,
            "rollout_steps": 2048,
            "minibatch_size": 512,
            "ent_coef": 0.012,
        },
        {
            "name": "s16_pipe_8x8_pkg_west_bridge2_fixed",
            "grid_size": [8, 8],
            "map_seed": 404,
            "loop_prob": 0.35,
            "max_steps": 1700,
            "timesteps": 800_000,
            "fixed_starts": [[2, 3], [2, 4]],
            "fixed_package": [8, 7],
            "fixed_deliveries": [[8, 5], [9, 6]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 65_000,
            "min_timesteps_before_promotion": 140_000,
            "promotion_success_rate": 0.60,
            "continue_success_rate": 0.35,
            "actor_log_std": -0.25,
            "min_actor_log_std": -0.80,
            "rollout_steps": 2048,
            "minibatch_size": 512,
            "ent_coef": 0.012,
        },
        {
            "name": "s17_pipe_8x8_pkg_west_bridge3_fixed",
            "grid_size": [8, 8],
            "map_seed": 404,
            "loop_prob": 0.35,
            "max_steps": 1750,
            "timesteps": 850_000,
            "fixed_starts": [[2, 3], [2, 4]],
            "fixed_package": [8, 5],
            "fixed_deliveries": [[8, 3], [9, 4]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 60_000,
            "min_timesteps_before_promotion": 120_000,
            "promotion_success_rate": 0.60,
            "continue_success_rate": 0.35,
            "actor_log_std": -0.25,
            "min_actor_log_std": -0.80,
            "rollout_steps": 2048,
            "minibatch_size": 512,
            "ent_coef": 0.012,
        },
        {
            "name": "s19_pipe_8x8_pkg_west3_fixed",
            "grid_size": [8, 8],
            "map_seed": 404,
            "loop_prob": 0.35,
            "max_steps": 1800,
            "timesteps": 900_000,
            "fixed_starts": [[2, 3], [2, 4]],
            "fixed_package": [8, 3],
            "fixed_deliveries": [[11, 3], [12, 3]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 70_000,
            "min_timesteps_before_promotion": 100_000,
            "promotion_success_rate": 0.35,
            "continue_success_rate": 0.20,
            "actor_log_std": -0.25,
            "min_actor_log_std": -0.80,
            "rollout_steps": 2048,
            "minibatch_size": 512,
            "ent_coef": 0.012,
        },
        {
            "name": "s24_pipe_8x8_mid_short_delivery_fixed",
            "grid_size": [8, 8],
            "map_seed": 404,
            "loop_prob": 0.35,
            "max_steps": 1800,
            "timesteps": 850_000,
            "fixed_starts": [[2, 3], [2, 4]],
            "fixed_package": [11, 2],
            "fixed_deliveries": [[14, 3], [15, 2]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 70_000,
            "min_timesteps_before_promotion": 120_000,
            "promotion_success_rate": 0.60,
            "continue_success_rate": 0.35,
            "actor_log_std": -0.25,
            "min_actor_log_std": -0.80,
            "rollout_steps": 2048,
            "minibatch_size": 512,
            "ent_coef": 0.012,
        },
        {
            "name": "s24a_pipe_8x8_mid_delivery_bridge5_fixed",
            "grid_size": [8, 8],
            "map_seed": 404,
            "loop_prob": 0.35,
            "max_steps": 1850,
            "timesteps": 1_000_000,
            "fixed_starts": [[2, 3], [2, 4]],
            "fixed_package": [11, 2],
            "fixed_deliveries": [[14, 4], [15, 3]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 70_000,
            "min_timesteps_before_promotion": 120_000,
            "promotion_success_rate": 0.60,
            "continue_success_rate": 0.35,
            "actor_log_std": -0.22,
            "min_actor_log_std": -0.90,
            "rollout_steps": 2048,
            "minibatch_size": 512,
            "ent_coef": 0.014,
        },
        {
            "name": "s24b_pipe_8x8_mid_delivery_bridge6_fixed",
            "grid_size": [8, 8],
            "map_seed": 404,
            "loop_prob": 0.35,
            "max_steps": 1850,
            "timesteps": 1_050_000,
            "fixed_starts": [[2, 3], [2, 4]],
            "fixed_package": [11, 2],
            "fixed_deliveries": [[14, 5], [15, 4]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 70_000,
            "min_timesteps_before_promotion": 120_000,
            "promotion_success_rate": 0.60,
            "continue_success_rate": 0.35,
            "actor_log_std": -0.20,
            "min_actor_log_std": -0.90,
            "rollout_steps": 2048,
            "minibatch_size": 512,
            "ent_coef": 0.014,
        },
        {
            "name": "s24c_pipe_8x8_mid_delivery_bridge8_fixed",
            "grid_size": [8, 8],
            "map_seed": 404,
            "loop_prob": 0.35,
            "max_steps": 1900,
            "timesteps": 1_000_000,
            "fixed_starts": [[2, 3], [2, 4]],
            "fixed_package": [11, 2],
            "fixed_deliveries": [[14, 7], [15, 6]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 75_000,
            "min_timesteps_before_promotion": 140_000,
            "promotion_success_rate": 0.60,
            "continue_success_rate": 0.35,
            "actor_log_std": -0.25,
            "min_actor_log_std": -0.80,
            "rollout_steps": 2048,
            "minibatch_size": 512,
            "ent_coef": 0.010,
        },
        {
            "name": "s24d_pipe_8x8_mid_delivery_bridge9_fixed",
            "grid_size": [8, 8],
            "map_seed": 404,
            "loop_prob": 0.35,
            "max_steps": 1900,
            "timesteps": 900_000,
            "fixed_starts": [[2, 3], [2, 4]],
            "fixed_package": [11, 2],
            "fixed_deliveries": [[14, 8], [15, 7]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 75_000,
            "min_timesteps_before_promotion": 140_000,
            "promotion_success_rate": 0.60,
            "continue_success_rate": 0.35,
            "actor_log_std": -0.22,
            "min_actor_log_std": -0.90,
            "rollout_steps": 2048,
            "minibatch_size": 512,
            "ent_coef": 0.014,
        },
        {
            "name": "s24e_pipe_8x8_mid_delivery_agent0_final_fixed",
            "grid_size": [8, 8],
            "map_seed": 404,
            "loop_prob": 0.35,
            "max_steps": 1900,
            "timesteps": 900_000,
            "fixed_starts": [[2, 3], [2, 4]],
            "fixed_package": [11, 2],
            "fixed_deliveries": [[15, 8], [15, 7]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 75_000,
            "min_timesteps_before_promotion": 140_000,
            "promotion_success_rate": 0.60,
            "continue_success_rate": 0.35,
            "actor_log_std": -0.22,
            "min_actor_log_std": -0.90,
            "rollout_steps": 2048,
            "minibatch_size": 512,
            "ent_coef": 0.014,
        },
        {
            "name": "s24f_pipe_8x8_mid_delivery_agent1_final_fixed",
            "grid_size": [8, 8],
            "map_seed": 404,
            "loop_prob": 0.35,
            "max_steps": 1900,
            "timesteps": 900_000,
            "fixed_starts": [[2, 3], [2, 4]],
            "fixed_package": [11, 2],
            "fixed_deliveries": [[15, 8], [14, 9]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 75_000,
            "min_timesteps_before_promotion": 140_000,
            "promotion_success_rate": 0.60,
            "continue_success_rate": 0.35,
            "actor_log_std": -0.22,
            "min_actor_log_std": -0.90,
            "rollout_steps": 2048,
            "minibatch_size": 512,
            "ent_coef": 0.014,
        },
        {
            "name": "s25_pipe_8x8_mid_fixed",
            "grid_size": [8, 8],
            "map_seed": 404,
            "loop_prob": 0.35,
            "max_steps": 1900,
            "timesteps": 1_050_000,
            "fixed_starts": [[2, 3], [2, 4]],
            "fixed_package": [11, 2],
            "fixed_deliveries": [[15, 8], [14, 9]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 75_000,
            "min_timesteps_before_promotion": 120_000,
            "promotion_success_rate": 0.60,
            "continue_success_rate": 0.40,
            "rollout_steps": 2048,
            "minibatch_size": 512,
            "ent_coef": 0.008,
        },
        {
            "name": "s25a_pipe_8x8_pkg_step1_fixed",
            "grid_size": [8, 8],
            "map_seed": 404,
            "loop_prob": 0.35,
            "max_steps": 2100,
            "timesteps": 900_000,
            "fixed_starts": [[2, 3], [2, 4]],
            "fixed_package": [12, 2],
            "fixed_deliveries": [[15, 8], [14, 9]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 80_000,
            "min_timesteps_before_promotion": 140_000,
            "promotion_success_rate": 0.60,
            "continue_success_rate": 0.35,
            "actor_log_std": -0.12,
            "min_actor_log_std": -0.65,
            "pickup_reward": 250.0,
            "rollout_steps": 2048,
            "minibatch_size": 512,
            "ent_coef": 0.020,
        },
        {
            "name": "s25a1_pipe_8x8_pkg_step2_fixed",
            "grid_size": [8, 8],
            "map_seed": 404,
            "loop_prob": 0.35,
            "max_steps": 2100,
            "timesteps": 700_000,
            "fixed_starts": [[2, 3], [2, 4]],
            "fixed_package": [13, 2],
            "fixed_deliveries": [[15, 8], [14, 9]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 70_000,
            "min_timesteps_before_promotion": 100_000,
            "promotion_success_rate": 0.35,
            "continue_success_rate": 0.20,
            "actor_log_std": -0.05,
            "min_actor_log_std": -0.55,
            "pickup_reward": 400.0,
            "learning_rate": 1e-4,
            "rollout_steps": 2048,
            "minibatch_size": 512,
            "ent_coef": 0.035,
        },
        {
            "name": "s25a2_pipe_8x8_pkg_step3_fixed",
            "grid_size": [8, 8],
            "map_seed": 404,
            "loop_prob": 0.35,
            "max_steps": 2150,
            "timesteps": 700_000,
            "fixed_starts": [[2, 3], [2, 4]],
            "fixed_package": [13, 3],
            "fixed_deliveries": [[15, 8], [14, 9]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 70_000,
            "min_timesteps_before_promotion": 100_000,
            "promotion_success_rate": 0.35,
            "continue_success_rate": 0.20,
            "actor_log_std": -0.05,
            "min_actor_log_std": -0.55,
            "pickup_reward": 400.0,
            "learning_rate": 1e-4,
            "rollout_steps": 2048,
            "minibatch_size": 512,
            "ent_coef": 0.035,
        },
        {
            "name": "s25a3_pipe_8x8_pkg_step4_fixed",
            "grid_size": [8, 8],
            "map_seed": 404,
            "loop_prob": 0.35,
            "max_steps": 2150,
            "timesteps": 750_000,
            "fixed_starts": [[2, 3], [2, 4]],
            "fixed_package": [14, 2],
            "fixed_deliveries": [[15, 8], [14, 9]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 70_000,
            "min_timesteps_before_promotion": 100_000,
            "promotion_success_rate": 0.35,
            "continue_success_rate": 0.20,
            "actor_log_std": -0.05,
            "min_actor_log_std": -0.55,
            "pickup_reward": 400.0,
            "learning_rate": 1e-4,
            "rollout_steps": 2048,
            "minibatch_size": 512,
            "ent_coef": 0.035,
        },
        {
            "name": "s25a4_pipe_8x8_pkg_step5_fixed",
            "grid_size": [8, 8],
            "map_seed": 404,
            "loop_prob": 0.35,
            "max_steps": 2200,
            "timesteps": 750_000,
            "fixed_starts": [[2, 3], [2, 4]],
            "fixed_package": [14, 3],
            "fixed_deliveries": [[15, 8], [14, 9]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 70_000,
            "min_timesteps_before_promotion": 100_000,
            "promotion_success_rate": 0.35,
            "continue_success_rate": 0.20,
            "actor_log_std": -0.05,
            "min_actor_log_std": -0.55,
            "pickup_reward": 400.0,
            "learning_rate": 1e-4,
            "rollout_steps": 2048,
            "minibatch_size": 512,
            "ent_coef": 0.035,
        },
        {
            "name": "s25a4b_pipe_8x8_delivery_step5_fixed",
            "grid_size": [8, 8],
            "map_seed": 404,
            "loop_prob": 0.35,
            "max_steps": 2200,
            "timesteps": 750_000,
            "fixed_starts": [[2, 3], [2, 4]],
            "fixed_package": [14, 3],
            "fixed_deliveries": [[14, 8], [15, 7]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 70_000,
            "min_timesteps_before_promotion": 100_000,
            "promotion_success_rate": 0.35,
            "continue_success_rate": 0.20,
            "actor_log_std": -0.05,
            "min_actor_log_std": -0.55,
            "pickup_reward": 400.0,
            "learning_rate": 1e-4,
            "rollout_steps": 2048,
            "minibatch_size": 512,
            "ent_coef": 0.035,
        },
        {
            "name": "s25a5_pipe_8x8_pkg_step6_fixed",
            "grid_size": [8, 8],
            "map_seed": 404,
            "loop_prob": 0.35,
            "max_steps": 2200,
            "timesteps": 800_000,
            "fixed_starts": [[2, 3], [2, 4]],
            "fixed_package": [15, 3],
            "fixed_deliveries": [[14, 9], [15, 8]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 80_000,
            "min_timesteps_before_promotion": 120_000,
            "promotion_success_rate": 0.35,
            "continue_success_rate": 0.20,
            "actor_log_std": -0.05,
            "min_actor_log_std": -0.55,
            "pickup_reward": 400.0,
            "learning_rate": 1e-4,
            "rollout_steps": 2048,
            "minibatch_size": 512,
            "ent_coef": 0.035,
        },
        {
            "name": "s25b_pipe_8x8_pkg_far_delivery_near_fixed",
            "grid_size": [8, 8],
            "map_seed": 404,
            "loop_prob": 0.35,
            "max_steps": 2200,
            "timesteps": 900_000,
            "fixed_starts": [[2, 3], [2, 4]],
            "fixed_package": [15, 4],
            "fixed_deliveries": [[14, 9], [15, 10]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 80_000,
            "min_timesteps_before_promotion": 120_000,
            "promotion_success_rate": 0.35,
            "continue_success_rate": 0.20,
            "actor_log_std": -0.05,
            "min_actor_log_std": -0.55,
            "pickup_reward": 400.0,
            "learning_rate": 1e-4,
            "rollout_steps": 2048,
            "minibatch_size": 512,
            "ent_coef": 0.035,
        },
        {
            "name": "s25b1_pipe_8x8_delivery_near_fixed",
            "grid_size": [8, 8],
            "map_seed": 404,
            "loop_prob": 0.35,
            "max_steps": 2200,
            "timesteps": 850_000,
            "fixed_starts": [[2, 3], [2, 4]],
            "fixed_package": [16, 3],
            "fixed_deliveries": [[14, 9], [15, 10]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 80_000,
            "min_timesteps_before_promotion": 120_000,
            "promotion_success_rate": 0.60,
            "continue_success_rate": 0.35,
            "actor_log_std": -0.08,
            "min_actor_log_std": -0.60,
            "pickup_reward": 300.0,
            "learning_rate": 1e-4,
            "rollout_steps": 2048,
            "minibatch_size": 512,
            "ent_coef": 0.028,
        },
        {
            "name": "s25b2_pipe_8x8_delivery_near2_fixed",
            "grid_size": [8, 8],
            "map_seed": 404,
            "loop_prob": 0.35,
            "max_steps": 2300,
            "timesteps": 850_000,
            "fixed_starts": [[2, 3], [2, 4]],
            "fixed_package": [16, 3],
            "fixed_deliveries": [[15, 12], [14, 13]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 80_000,
            "min_timesteps_before_promotion": 120_000,
            "promotion_success_rate": 0.60,
            "continue_success_rate": 0.35,
            "actor_log_std": -0.08,
            "min_actor_log_std": -0.60,
            "pickup_reward": 300.0,
            "learning_rate": 1e-4,
            "rollout_steps": 2048,
            "minibatch_size": 512,
            "ent_coef": 0.028,
        },
        {
            "name": "s25c_pipe_8x8_delivery_farther_fixed",
            "grid_size": [8, 8],
            "map_seed": 404,
            "loop_prob": 0.35,
            "max_steps": 2400,
            "timesteps": 1_000_000,
            "fixed_starts": [[2, 3], [2, 4]],
            "fixed_package": [16, 3],
            "fixed_deliveries": [[20, 19], [21, 18]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 85_000,
            "min_timesteps_before_promotion": 160_000,
            "promotion_success_rate": 0.60,
            "continue_success_rate": 0.35,
            "actor_log_std": -0.12,
            "min_actor_log_std": -0.65,
            "rollout_steps": 2048,
            "minibatch_size": 512,
            "ent_coef": 0.020,
        },
        {
            "name": "s25d_pipe_8x8_delivery_near_final_fixed",
            "grid_size": [8, 8],
            "map_seed": 404,
            "loop_prob": 0.35,
            "max_steps": 2500,
            "timesteps": 1_000_000,
            "fixed_starts": [[2, 3], [2, 4]],
            "fixed_package": [16, 3],
            "fixed_deliveries": [[20, 24], [21, 23]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 85_000,
            "min_timesteps_before_promotion": 160_000,
            "promotion_success_rate": 0.60,
            "continue_success_rate": 0.35,
            "actor_log_std": -0.12,
            "min_actor_log_std": -0.65,
            "rollout_steps": 2048,
            "minibatch_size": 512,
            "ent_coef": 0.020,
        },
        {
            "name": "s26_pipe_8x8_far_fixed",
            "grid_size": [8, 8],
            "map_seed": 404,
            "loop_prob": 0.35,
            "max_steps": 2600,
            "timesteps": 1_100_000,
            "fixed_starts": [[2, 3], [2, 4]],
            "fixed_package": [16, 3],
            "fixed_deliveries": [[20, 29], [21, 28]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 90_000,
            "min_timesteps_before_promotion": 120_000,
            "promotion_success_rate": 0.55,
            "continue_success_rate": 0.35,
            "actor_log_std": -0.12,
            "min_actor_log_std": -0.65,
            "rollout_steps": 2048,
            "minibatch_size": 512,
            "ent_coef": 0.020,
        },
        {
            "name": "s27_pipe_10x10_fixed",
            "grid_size": [10, 10],
            "map_seed": 505,
            "loop_prob": 0.35,
            "max_steps": 3200,
            "timesteps": 1_300_000,
            "package_min_dist": 12,
            "package_max_dist": 30,
            "delivery_min_dist": 12,
            "delivery_max_dist": 38,
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 110_000,
            "min_timesteps_before_promotion": 120_000,
            "promotion_success_rate": 0.50,
            "continue_success_rate": 0.30,
            "rollout_steps": 2048,
            "minibatch_size": 512,
            "ent_coef": 0.008,
        },
        {
            "name": "s28_pipe_12x12_fixed",
            "grid_size": [12, 12],
            "map_seed": 606,
            "loop_prob": 0.35,
            "max_steps": 4000,
            "timesteps": 1_500_000,
            "package_min_dist": 14,
            "package_max_dist": 36,
            "delivery_min_dist": 14,
            "delivery_max_dist": 46,
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 130_000,
            "min_timesteps_before_promotion": 120_000,
            "promotion_success_rate": 0.45,
            "continue_success_rate": 0.25,
            "rollout_steps": 2048,
            "minibatch_size": 512,
            "ent_coef": 0.006,
        },
    ],
}

for stage in config["curriculum"]:
    if stage["name"].startswith(("s1_", "s2_", "s3_", "s4")):
        stage["actor_log_std"] = -0.35
        stage["min_actor_log_std"] = -1.00
        stage["ent_coef"] = max(float(stage.get("ent_coef", config["ent_coef"])), 0.006)
    else:
        stage["actor_log_std"] = -0.25
        stage["min_actor_log_std"] = -1.25
        stage["ent_coef"] = max(float(stage.get("ent_coef", config["ent_coef"])), 0.010)

for stage in config["curriculum"]:
    if stage["name"] == "s24a_pipe_8x8_mid_delivery_bridge5_fixed":
        stage["actor_log_std"] = -0.22
        stage["min_actor_log_std"] = -0.90
        stage["ent_coef"] = 0.014
    elif stage["name"] == "s24b_pipe_8x8_mid_delivery_bridge6_fixed":
        stage["actor_log_std"] = -0.20
        stage["min_actor_log_std"] = -0.90
        stage["ent_coef"] = 0.014
    elif stage["name"] in {
        "s24d_pipe_8x8_mid_delivery_bridge9_fixed",
        "s24e_pipe_8x8_mid_delivery_agent0_final_fixed",
        "s24f_pipe_8x8_mid_delivery_agent1_final_fixed",
        "s25_pipe_8x8_mid_fixed",
    }:
        stage["actor_log_std"] = -0.22
        stage["min_actor_log_std"] = -0.90
        stage["ent_coef"] = 0.014
    elif stage["name"] in {
        "s25a_pipe_8x8_pkg_step1_fixed",
        "s25c_pipe_8x8_delivery_farther_fixed",
        "s25d_pipe_8x8_delivery_near_final_fixed",
        "s26_pipe_8x8_far_fixed",
    }:
        stage["actor_log_std"] = -0.12
        stage["min_actor_log_std"] = -0.65
        stage["ent_coef"] = 0.020
    elif stage["name"] in {
        "s25a1_pipe_8x8_pkg_step2_fixed",
        "s25a2_pipe_8x8_pkg_step3_fixed",
        "s25a3_pipe_8x8_pkg_step4_fixed",
        "s25a4_pipe_8x8_pkg_step5_fixed",
        "s25a4b_pipe_8x8_delivery_step5_fixed",
        "s25a5_pipe_8x8_pkg_step6_fixed",
        "s25b_pipe_8x8_pkg_far_delivery_near_fixed",
        "s25b1_pipe_8x8_delivery_near_fixed",
        "s25b2_pipe_8x8_delivery_near2_fixed",
    }:
        if stage["name"] in {
            "s25b1_pipe_8x8_delivery_near_fixed",
            "s25b2_pipe_8x8_delivery_near2_fixed",
        }:
            stage["actor_log_std"] = -0.08
            stage["min_actor_log_std"] = -0.60
            stage["ent_coef"] = 0.028
            stage["pickup_reward"] = max(float(stage.get("pickup_reward", config["pickup_reward"])), 300.0)
        else:
            stage["actor_log_std"] = -0.05
            stage["min_actor_log_std"] = -0.55
            stage["ent_coef"] = 0.035
            stage["pickup_reward"] = max(float(stage.get("pickup_reward", config["pickup_reward"])), 400.0)
        stage["learning_rate"] = min(float(stage.get("learning_rate", config["learning_rate"])), 1e-4)

config["total_timesteps"] = sum(stage["timesteps"] for stage in config["curriculum"])
