try:
    from envs.multi_quadcopter_drone_env import ENV_DEFAULTS
except ImportError:
    from quad_physics.envs.multi_quadcopter_drone_env import ENV_DEFAULTS


# Physics constants — fixed across all stages so the policy never has to
# re-learn locomotion when the navigation curriculum advances.
FIXED_MAX_TILT = 0.35
FIXED_LINEAR_DRAG = 0.88


config = {
    **ENV_DEFAULTS,
    "run_name": "quad_physics_mappo_v1_random_delivery",
    "seed": 7,
    "device": "auto",
    "rollout_steps": 1024,
    "epochs": 6,
    "minibatch_size": 256,
    "learning_rate": 3e-4,
    "gamma": 0.99,
    "gae_lambda": 0.95,
    "clip_range": 0.15,
    "ent_coef": 0.004,
    "vf_coef": 0.5,
    "max_grad_norm": 0.5,
    "hidden_size": 128,
    "progress_print_freq": 10_000,
    "stage_eval_every": 25_000,
    "stage_eval_episodes": 20,
    "stage_promotion_success_rate": 0.70,
    "stage_min_timesteps_before_promotion": 50_000,
    "viz_enabled": True,
    "viz_delay": 0.12,
    "viz_save_path": "mappo_quad_rollout.gif",
    "viz_save_images": True,
    "viz_image_dir": "mappo_quad_rollout_images",
    "viz_show": False,
    "curriculum": [
        # ------------------------------------------------------------------
        # T-JUNCTION STAGES  (fixed map, progressively harder delivery goals)
        # ------------------------------------------------------------------
        {
            "name": "s1_short_t_fixed",
            "map_layout": "t_junction",
            "stem_length": 4,
            "branch_left": 1,
            "branch_right": 1,
            "map_padding": 1,
            "max_steps": 120,
            "timesteps": 180_000,
            "fixed_starts": [[4, 2], [3, 2]],
            "fixed_package": [2, 2],
            "fixed_deliveries": [[1, 1], [1, 3]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 20_000,
            "min_timesteps_before_promotion": 50_000,
            "promotion_success_rate": 0.90,
            "collision_penalty": 8.0,
            "revisit_penalty": 0.0,
            "revisit_penalty_cap": 0.0,
            "max_tilt": FIXED_MAX_TILT,
            "linear_drag": FIXED_LINEAR_DRAG,
        },
        {
            "name": "s2_wider_t_stem_fixed",
            # Same wide T, deliveries still along the stem — easy navigation.
            "map_layout": "t_junction",
            "stem_length": 6,
            "branch_left": 3,
            "branch_right": 3,
            "map_padding": 1,
            "max_steps": 220,
            "timesteps": 400_000,
            "fixed_starts": [[6, 4], [5, 4]],
            "fixed_package": [3, 4],
            "fixed_deliveries": [[2, 4], [1, 4]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 25_000,
            "min_timesteps_before_promotion": 70_000,
            "promotion_success_rate": 0.85,
            "collision_penalty": 8.0,
            "revisit_penalty": 0.0,
            "revisit_penalty_cap": 0.0,
            "max_tilt": FIXED_MAX_TILT,
            "linear_drag": FIXED_LINEAR_DRAG,
        },
        {
            "name": "s3_wider_t_near_branch_fixed",
            # Package at junction, deliveries just inside branch tips.
            "map_layout": "t_junction",
            "stem_length": 6,
            "branch_left": 3,
            "branch_right": 3,
            "map_padding": 1,
            "max_steps": 280,
            "timesteps": 600_000,
            "fixed_starts": [[6, 4], [5, 4]],
            "fixed_package": [2, 4],
            "fixed_deliveries": [[1, 3], [1, 5]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 25_000,
            "min_timesteps_before_promotion": 70_000,
            "promotion_success_rate": 0.75,
            "collision_penalty": 8.0,
            "revisit_penalty": 0.0,
            "revisit_penalty_cap": 0.0,
            "max_tilt": FIXED_MAX_TILT,
            "linear_drag": FIXED_LINEAR_DRAG,
        },
        {
            "name": "s3b_wider_t_near_branch_repeat_fixed",
            "map_layout": "t_junction",
            "stem_length": 6,
            "branch_left": 3,
            "branch_right": 3,
            "map_padding": 1,
            "max_steps": 300,
            "timesteps": 400_000,
            "fixed_starts": [[6, 4], [5, 4]],
            "fixed_package": [2, 4],
            "fixed_deliveries": [[1, 3], [1, 5]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 25_000,
            "min_timesteps_before_promotion": 70_000,
            "promotion_success_rate": 0.75,
            "max_tilt": FIXED_MAX_TILT,
            "linear_drag": FIXED_LINEAR_DRAG,
        },
        {
            "name": "s4a_left_wider_t_mid_branch_fixed",
            # Move one delivery outward first; doing both at once often traps at one delivery.
            "map_layout": "t_junction",
            "stem_length": 6,
            "branch_left": 3,
            "branch_right": 3,
            "map_padding": 1,
            "max_steps": 300,
            "timesteps": 420_000,
            "fixed_starts": [[6, 4], [5, 4]],
            "fixed_package": [3, 4],
            "fixed_deliveries": [[1, 2], [1, 5]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 25_000,
            "min_timesteps_before_promotion": 70_000,
            "promotion_success_rate": 0.75,
            "max_tilt": FIXED_MAX_TILT,
            "linear_drag": FIXED_LINEAR_DRAG,
        },
        {
            "name": "s4b_right_wider_t_mid_branch_fixed",
            "map_layout": "t_junction",
            "stem_length": 6,
            "branch_left": 3,
            "branch_right": 3,
            "map_padding": 1,
            "max_steps": 300,
            "timesteps": 420_000,
            "fixed_starts": [[6, 4], [5, 4]],
            "fixed_package": [3, 4],
            "fixed_deliveries": [[1, 3], [1, 6]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 25_000,
            "min_timesteps_before_promotion": 70_000,
            "promotion_success_rate": 0.75,
            "max_tilt": FIXED_MAX_TILT,
            "linear_drag": FIXED_LINEAR_DRAG,
        },
        {
            "name": "s4c_wider_t_mid_branch_fixed",
            "map_layout": "t_junction",
            "stem_length": 6,
            "branch_left": 3,
            "branch_right": 3,
            "map_padding": 1,
            "max_steps": 320,
            "timesteps": 560_000,
            "fixed_starts": [[6, 4], [5, 4]],
            "fixed_package": [3, 4],
            "fixed_deliveries": [[1, 2], [1, 6]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 25_000,
            "min_timesteps_before_promotion": 80_000,
            "promotion_success_rate": 0.70,
            "max_tilt": FIXED_MAX_TILT,
            "linear_drag": FIXED_LINEAR_DRAG,
        },
        {
            "name": "s4d_wider_t_far_branch_fixed",
            # Original s4 goal: full branch tips.
            "map_layout": "t_junction",
            "stem_length": 6,
            "branch_left": 3,
            "branch_right": 3,
            "map_padding": 1,
            "max_steps": 300,
            "timesteps": 700_000,
            "fixed_starts": [[6, 4], [5, 4]],
            "fixed_package": [3, 4],
            "fixed_deliveries": [[1, 1], [1, 7]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 25_000,
            "min_timesteps_before_promotion": 70_000,
            "promotion_success_rate": 0.70,
            "max_tilt": FIXED_MAX_TILT,
            "linear_drag": FIXED_LINEAR_DRAG,
        },
        {
            "name": "s4e_wider_t_far_branch_random_delivery",
            "map_layout": "t_junction",
            "stem_length": 6,
            "branch_left": 3,
            "branch_right": 3,
            "map_padding": 1,
            "max_steps": 320,
            "timesteps": 500_000,
            "fixed_starts": [[6, 4], [5, 4]],
            "fixed_package": [3, 4],
            "fixed_deliveries": [[1, 1], [1, 7]],  # fallback
            "randomize_package": False,
            "randomize_deliveries": True,
            "delivery_min_dist": 2,
            "delivery_max_dist": 6,
            "eval_every": 25_000,
            "min_timesteps_before_promotion": 70_000,
            "promotion_success_rate": 0.65,
            "continue_success_rate": 0.45,
            "max_tilt": FIXED_MAX_TILT,
            "linear_drag": FIXED_LINEAR_DRAG,
        },
        {
            "name": "s5a_wider_t_fixed_package",
            "map_layout": "t_junction",
            "stem_length": 7,
            "branch_left": 4,
            "branch_right": 4,
            "map_padding": 1,
            "max_steps": 360,
            "timesteps": 420_000,
            "fixed_starts": [[7, 5], [6, 5]],
            "fixed_package": [3, 5],
            "fixed_deliveries": [[1, 1], [1, 9]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 30_000,
            "min_timesteps_before_promotion": 70_000,
            "promotion_success_rate": 0.65,
            "continue_success_rate": 0.35,
            "max_tilt": FIXED_MAX_TILT,
            "linear_drag": FIXED_LINEAR_DRAG,
        },
        {
            "name": "s5b_wider_t_near_random_package",
            "map_layout": "t_junction",
            "stem_length": 7,
            "branch_left": 4,
            "branch_right": 4,
            "map_padding": 1,
            "max_steps": 380,
            "timesteps": 650_000,
            "fixed_starts": [[7, 5], [6, 5]],
            "fixed_package": [3, 5],
            "fixed_deliveries": [[1, 1], [1, 9]],
            "package_min_dist": 2,
            "package_max_dist": 3,
            "delivery_min_dist": 3,
            "delivery_max_dist": 8,
            "randomize_package": True,
            "randomize_deliveries": False,
            "eval_every": 30_000,
            "min_timesteps_before_promotion": 70_000,
            "promotion_success_rate": 0.45,
            "continue_success_rate": 0.30,
            "max_tilt": FIXED_MAX_TILT,
            "linear_drag": FIXED_LINEAR_DRAG,
        },
        {
            "name": "s5c_wider_t_random_package",
            "map_layout": "t_junction",
            "stem_length": 7,
            "branch_left": 4,
            "branch_right": 4,
            "map_padding": 1,
            "max_steps": 420,
            "timesteps": 850_000,
            "fixed_starts": [[7, 5], [6, 5]],
            "fixed_package": [3, 5],
            "fixed_deliveries": [[1, 1], [1, 9]],
            "package_min_dist": 2,
            "package_max_dist": 5,
            "delivery_min_dist": 3,
            "delivery_max_dist": 8,
            "randomize_package": True,
            "randomize_deliveries": False,
            "eval_every": 35_000,
            "min_timesteps_before_promotion": 90_000,
            "promotion_success_rate": 0.45,
            "continue_success_rate": 0.30,
            "max_tilt": FIXED_MAX_TILT,
            "linear_drag": FIXED_LINEAR_DRAG,
        },
        # ------------------------------------------------------------------
        # PIPE / MAZE STAGES  (map-generated corridors, increasing grid size)
        # ------------------------------------------------------------------
        {
            "name": "s6_tiny_pipe_fixed",
            "grid_size": [2, 2],
            "map_seed": 42,
            "loop_prob": 0.25,
            "max_steps": 260,
            "timesteps": 260_000,
            "fixed_starts": [[2, 3], [2, 4]],
            "fixed_package": [2, 5],
            "fixed_deliveries": [[2, 6], [2, 7]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 25_000,
            "min_timesteps_before_promotion": 70_000,
            "promotion_success_rate": 0.80,
            "max_tilt": FIXED_MAX_TILT,
            "linear_drag": FIXED_LINEAR_DRAG,
            "actor_log_std": -0.35,
            "min_actor_log_std": -0.75,
            "collision_penalty": 8.0,
        },
        {
            "name": "s7_small_pipe_line_fixed",
            "grid_size": [3, 3],
            "map_seed": 101,
            "loop_prob": 0.25,
            "max_steps": 360,
            "timesteps": 360_000,
            "fixed_starts": [[2, 3], [2, 4]],
            "fixed_package": [2, 6],
            "fixed_deliveries": [[2, 8], [2, 9]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 25_000,
            "min_timesteps_before_promotion": 80_000,
            "promotion_success_rate": 0.80,
            "max_tilt": FIXED_MAX_TILT,
            "linear_drag": FIXED_LINEAR_DRAG,
            "actor_log_std": -0.35,
            "min_actor_log_std": -0.75,
            "collision_penalty": 8.0,
            "revisit_penalty": 0.0,
            "revisit_penalty_cap": 0.0,
        },
        {
            "name": "s8_small_pipe_vertical_fixed",
            "grid_size": [3, 3],
            "map_seed": 101,
            "loop_prob": 0.25,
            "max_steps": 360,
            "timesteps": 360_000,
            "fixed_starts": [[2, 8], [3, 8]],
            "fixed_package": [4, 8],
            "fixed_deliveries": [[5, 8], [6, 8]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 25_000,
            "min_timesteps_before_promotion": 80_000,
            "promotion_success_rate": 0.80,
            "max_tilt": FIXED_MAX_TILT,
            "linear_drag": FIXED_LINEAR_DRAG,
            "actor_log_std": -0.35,
            "min_actor_log_std": -0.75,
            "ent_coef": 0.012,
            "collision_penalty": 8.0,
            "revisit_penalty": 0.0,
            "revisit_penalty_cap": 0.0,
        },
        {
            "name": "s9_small_pipe_turn_fixed",
            "grid_size": [3, 3],
            "map_seed": 101,
            "loop_prob": 0.25,
            "max_steps": 460,
            "timesteps": 500_000,
            "fixed_starts": [[2, 6], [2, 7]],
            "fixed_package": [2, 8],
            "fixed_deliveries": [[4, 8], [5, 8]],
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 25_000,
            "min_timesteps_before_promotion": 80_000,
            "promotion_success_rate": 0.75,
            "max_tilt": FIXED_MAX_TILT,
            "linear_drag": FIXED_LINEAR_DRAG,
            "actor_log_std": -0.35,
            "min_actor_log_std": -0.75,
            "ent_coef": 0.012,
            "collision_penalty": 8.0,
            "revisit_penalty": 0.0,
            "revisit_penalty_cap": 0.0,
        },
        {
            "name": "s10_small_pipe_fixed",
            "grid_size": [3, 3],
            "map_seed": 101,
            "loop_prob": 0.25,
            "max_steps": 520,
            "timesteps": 880_000,
            "package_min_dist": 3,
            "package_max_dist": 7,
            "delivery_min_dist": 3,
            "delivery_max_dist": 9,
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 25_000,
            "min_timesteps_before_promotion": 80_000,
            "promotion_success_rate": 0.75,
            "max_tilt": FIXED_MAX_TILT,
            "linear_drag": FIXED_LINEAR_DRAG,
            "actor_log_std": -0.35,
            "min_actor_log_std": -0.75,
            "ent_coef": 0.010,
        },
        {
            "name": "s11_small_pipe_random_package",
            "grid_size": [3, 3],
            "map_seed": 101,
            "loop_prob": 0.25,
            "max_steps": 650,
            "timesteps": 1_200_000,
            "package_min_dist": 3,
            "package_max_dist": 7,
            "delivery_min_dist": 3,
            "delivery_max_dist": 9,
            "randomize_package": True,
            "randomize_deliveries": False,
            "eval_every": 30_000,
            "min_timesteps_before_promotion": 100_000,
            "promotion_success_rate": 0.55,
            "continue_success_rate": 0.50,
            "eval_episodes": 40,
            "max_tilt": FIXED_MAX_TILT,
            "linear_drag": FIXED_LINEAR_DRAG,
            "actor_log_std": -0.35,
            "min_actor_log_std": -0.80,
            "ent_coef": 0.010,
        },
        {
            "name": "s12_small_pipe_random_delivery",
            "grid_size": [3, 3],
            "map_seed": 101,
            "loop_prob": 0.25,
            "max_steps": 760,
            "timesteps": 700_000,
            "package_min_dist": 3,
            "package_max_dist": 7,
            "delivery_min_dist": 3,
            "delivery_max_dist": 10,
            "randomize_package": False,
            "randomize_deliveries": True,
            "eval_every": 40_000,
            "min_timesteps_before_promotion": 100_000,
            "promotion_success_rate": 0.60,
            "continue_success_rate": 0.50,
            "max_tilt": FIXED_MAX_TILT,
            "linear_drag": FIXED_LINEAR_DRAG,
            "actor_log_std": -0.35,
            "min_actor_log_std": -0.80,
            "ent_coef": 0.012,
        },
        {
            "name": "s13_small_pipe_random_package_delivery",
            "grid_size": [3, 3],
            "map_seed": 101,
            "loop_prob": 0.25,
            "max_steps": 800,
            "timesteps": 850_000,
            "package_min_dist": 3,
            "package_max_dist": 7,
            "delivery_min_dist": 3,
            "delivery_max_dist": 10,
            "randomize_package": True,
            "randomize_deliveries": True,
            "eval_every": 45_000,
            "min_timesteps_before_promotion": 100_000,
            "promotion_success_rate": 0.65,
            "continue_success_rate": 0.50,
            "max_tilt": FIXED_MAX_TILT,
            "linear_drag": FIXED_LINEAR_DRAG,
            "actor_log_std": -0.35,
            "min_actor_log_std": -0.80,
            "ent_coef": 0.012,
        },
        # ------------------------------------------------------------------
        # MEDIUM PIPE STAGES
        # ------------------------------------------------------------------
        {
            "name": "s14_medium_pipe_fixed",
            "grid_size": [4, 4],
            "map_seed": 202,
            "loop_prob": 0.30,
            "max_steps": 950,
            "timesteps": 850_000,
            "package_min_dist": 5,
            "package_max_dist": 12,
            "delivery_min_dist": 5,
            "delivery_max_dist": 16,
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 40_000,
            "min_timesteps_before_promotion": 100_000,
            "promotion_success_rate": 0.70,
            "max_tilt": FIXED_MAX_TILT,
            "linear_drag": FIXED_LINEAR_DRAG,
            "ent_coef": 0.008,
        },
        {
            "name": "s15_medium_pipe_random_package",
            "grid_size": [4, 4],
            "map_seed": 202,
            "loop_prob": 0.30,
            "max_steps": 1100,
            "timesteps": 850_000,
            "package_min_dist": 5,
            "package_max_dist": 12,
            "delivery_min_dist": 5,
            "delivery_max_dist": 16,
            "randomize_package": True,
            "randomize_deliveries": False,
            "eval_every": 45_000,
            "min_timesteps_before_promotion": 100_000,
            "promotion_success_rate": 0.65,
            "max_tilt": FIXED_MAX_TILT,
            "linear_drag": FIXED_LINEAR_DRAG,
            "ent_coef": 0.010,
        },
        {
            "name": "s16_medium_pipe_random_package_delivery",
            "grid_size": [4, 4],
            "map_seed": 202,
            "loop_prob": 0.30,
            "max_steps": 1300,
            "timesteps": 900_000,
            "package_min_dist": 5,
            "package_max_dist": 12,
            "delivery_min_dist": 5,
            "delivery_max_dist": 16,
            "randomize_package": True,
            "randomize_deliveries": True,
            "eval_every": 50_000,
            "min_timesteps_before_promotion": 100_000,
            "promotion_success_rate": 0.60,
            "max_tilt": FIXED_MAX_TILT,
            "linear_drag": FIXED_LINEAR_DRAG,
            "ent_coef": 0.012,
        },
        # ------------------------------------------------------------------
        # LARGE PIPE STAGES
        # ------------------------------------------------------------------
        {
            "name": "s17_large_pipe_fixed",
            "grid_size": [6, 6],
            "map_seed": 303,
            "loop_prob": 0.30,
            "max_steps": 1800,
            "timesteps": 900_000,
            "package_min_dist": 8,
            "package_max_dist": 16,
            "delivery_min_dist": 7,
            "delivery_max_dist": 18,
            "randomize_package": False,
            "randomize_deliveries": False,
            "eval_every": 60_000,
            "min_timesteps_before_promotion": 100_000,
            "promotion_success_rate": 0.60,
            "max_tilt": FIXED_MAX_TILT,
            "linear_drag": FIXED_LINEAR_DRAG,
            "rollout_steps": 2048,
            "minibatch_size": 512,
            "ent_coef": 0.010,
        },
        {
            "name": "s18_large_pipe_random_package",
            "grid_size": [6, 6],
            "map_seed": 303,
            "loop_prob": 0.30,
            "max_steps": 2200,
            "timesteps": 1_000_000,
            "package_min_dist": 8,
            "package_max_dist": 18,
            "delivery_min_dist": 7,
            "delivery_max_dist": 20,
            "randomize_package": True,
            "randomize_deliveries": False,
            "eval_every": 75_000,
            "min_timesteps_before_promotion": 100_000,
            "promotion_success_rate": 0.55,
            "max_tilt": FIXED_MAX_TILT,
            "linear_drag": FIXED_LINEAR_DRAG,
            "rollout_steps": 2048,
            "minibatch_size": 512,
            "ent_coef": 0.010,
        },
        {
            "name": "s19_large_pipe_random_package_delivery",
            "grid_size": [6, 6],
            "map_seed": 303,
            "loop_prob": 0.30,
            "max_steps": 2600,
            "timesteps": 1_500_000,
            "package_min_dist": 8,
            "package_max_dist": 20,
            "delivery_min_dist": 8,
            "delivery_max_dist": 24,
            "randomize_package": True,
            "randomize_deliveries": True,
            "eval_every": 100_000,
            "min_timesteps_before_promotion": 100_000,
            "promotion_success_rate": 0.50,
            "max_tilt": FIXED_MAX_TILT,
            "linear_drag": FIXED_LINEAR_DRAG,
            "rollout_steps": 2048,
            "minibatch_size": 512,
            "ent_coef": 0.010,
        },
        # ------------------------------------------------------------------
        # XL STAGE
        # ------------------------------------------------------------------
        {
            "name": "s20_xlarge_pipe_random_package_delivery",
            "grid_size": [8, 8],
            "map_seed": 404,
            "loop_prob": 0.35,
            "max_steps": 3600,
            "timesteps": 1_500_000,
            "package_min_dist": 10,
            "package_max_dist": 26,
            "delivery_min_dist": 10,
            "delivery_max_dist": 32,
            "randomize_package": True,
            "randomize_deliveries": True,
            "eval_every": 120_000,
            "min_timesteps_before_promotion": 500_000,
            "promotion_success_rate": 0.45,
            "max_tilt": FIXED_MAX_TILT,
            "linear_drag": FIXED_LINEAR_DRAG,
            "rollout_steps": 2048,
            "minibatch_size": 512,
            "ent_coef": 0.008,
        },
    ],
}
config["total_timesteps"] = sum(stage["timesteps"] for stage in config["curriculum"])
